### ISSUE TITLE
您好 代码运行问题

### ISSUE THREAD

**Issue by fannn1217** [PY131/Tianchi-BigData#1]
您好我在运行Tianchi-BigData/Mobile_Recommendation/model_based/gbdt_on_subsample.py时出现了这样的问题
Traceback (most recent call last):
  File "gbdt_on_subsample.py", line 726, in <module>
    GBDT_clf.fit(train_X, train_y)
  File "/Library/Python/2.7/site-packages/sklearn/ensemble/gradient_boosting.py", line 991, in fit
    self._check_params()
  File "/Library/Python/2.7/site-packages/sklearn/ensemble/gradient_boosting.py", line 829, in _check_params
    self.loss_ = loss_class(self.n_classes_)
  File "/Library/Python/2.7/site-packages/sklearn/ensemble/gradient_boosting.py", line 472, in __init__
    self.__class__.__name__))
ValueError: BinomialDeviance requires 2 classes.
请问是为什么呢

**Comment by PnYuan** [comment]
@fannn1217 
你好，这段代码的运行环境是python 3.6+sklearn 0.18.1，不清楚python2.7环境会不会影响。
怎么我这边程序是正常运行的呢o(∩_∩)o 。

**Comment by xiaoshanhu** [comment]
我也遇到了这个问题，请问您解决了嘛？

**Comment by HenryBao91** [comment]
Traceback (most recent call last):
  File "D:\Python\lib\site-packages\pandas\core\indexes\base.py", line 3078, in get_loc
    return self._engine.get_loc(key)
  File "pandas\_libs\index.pyx", line 140, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 162, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1492, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1500, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Python\data_anlysis.py", line 189, in <module>
    df_1718[3].plot(kind='bar', color = 'r')
  File "D:\Python\lib\site-packages\pandas\core\frame.py", line 2688, in __getitem__
    return self._getitem_column(key)
  File "D:\Python\lib\site-packages\pandas\core\frame.py", line 2695, in _getitem_column
    return self._get_item_cache(key)
  File "D:\Python\lib\site-packages\pandas\core\generic.py", line 2489, in _get_item_cache
    values = self._data.get(item)
  File "D:\Python\lib\site-packages\pandas\core\internals.py", line 4115, in get
    loc = self.items.get_loc(item)
  File "D:\Python\lib\site-packages\pandas\core\indexes\base.py", line 3080, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas\_libs\index.pyx", line 140, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 162, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1492, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1500, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 3
[Finished in 740.2s with exit code 1]
[shell_cmd: python -u "F:\Python\data_anlysis.py"]
[dir: F:\Python]

我遇到了同样的问题，求助

**Comment by xiaoshanhu** [comment]
换成python3吧，我换了python3就没问题了

**Comment by HenryBao91** [comment]
@xiaoshanhu 我的是Python3，Python3.6+sklearn1.9.2 。
